import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

import { QueryProvider } from '@/providers/QueryProvider';
import { Toaster } from '@/components/ui/toaster';
import { Navbar } from '@/components/common/Navbar';

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Toaster />
        <QueryProvider>
          <div className='mt-10 container mx-auto w-full'>
            <Navbar />
            {children}
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
