import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

import { QueryProvider } from '@/providers/QueryProvider';
import { Toaster } from '@/components/ui/toaster';
import { Sidebar } from '@/components/common/Sidebar';
import { SidebarProvider } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/common/app-sidebar';

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Toaster />
        <QueryProvider>
          <SidebarProvider>
            <AppSidebar />
            <main className='w-full p-4 bg-gray-50 min-h-screen'>
              {children}
            </main>
          </SidebarProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
